version: '2'
services:
    jellyfin:
        image: linuxserver/jellyfin
        container_name: jellyfin
        restart: unless-stopped
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        networks:
          - default
        volumes:
          - /mediaServer/jellyfin/config:/config
          - /Media/jellyfin/media:/media
        ports:
          - 8096:8096
    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        restart: unless-stopped
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        volumes:
            - /Media/nzbget/config:/config
            - /Media/nzbget/downloads:/downloads
        ports:
            - 6789:6789
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: unless-stopped
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        depends_on:
            - nzbget
        volumes:
            - /mediaServer/sonarr/config:/config
            - /Media/nzbget/downloads:/downloads
            - /Media/jellyfin/media/Shows:/tv
        ports:
            - 8989:8989
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: unless-stopped
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        depends_on:
            - nzbget
        volumes:
            - /mediaServer/radarr/config:/config
            - /Media/nzbget/downloads:/downloads
            - /Media/jellyfin/media/Movies:/movies
        ports:
            - 7878:7878
    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        restart: unless-stopped
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "80:80/tcp"
        environment:
          TZ: Europe/Dublin
          WEBPASSWORD: $PIPASSWORD
          DNSMASQ_LISTENING: local
          PIHOLE_DNS_: 1.1.1.1;1.1.0.0
        # Volumes store your data between container upgrades
        volumes:
          - './etc-pihole:/etc/pihole'
          - './etc-dnsmasq.d:/etc/dnsmasq.d'