networks:
  media_network:
    driver: bridge
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"   # video
      - "107"  # render
    environment:
      TZ: Europe/Dublin
    networks:
      - media_network
    ports:
      - '8096:8096'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/jellyfin/config:/config
      - ${DATA_LOCATION}/jellyfin/media:/media
      - ${CACHE_LOCATION}/jellyfin/transcodes:/transcodes
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  radarr:
    container_name: radarr
    depends_on:
      - sabnzbd
    environment:
      TZ: Europe/Dublin
    image: linuxserver/radarr
    networks:
      - media_network
    ports:
      - '7878:7878'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/radarr/config:/config
      - ${CACHE_LOCATION}/sabnzbd/downloads:/downloads
      - ${DATA_LOCATION}/jellyfin/media/Movies:/movies
  sabnzbd:
    container_name: sabnzbd
    environment:
      TZ: Europe/Dublin
    image: lscr.io/linuxserver/sabnzbd:latest
    networks:
      - media_network
    ports:
      - '6789:8080'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/sabnzbd/config:/config
      - ${CACHE_LOCATION}/sabnzbd/downloads:/downloads
      - ${CACHE_LOCATION}/sabnzbd/incomplete:/incomplete-downloads
  sonarr:
    container_name: sonarr
    depends_on:
      - sabnzbd
    environment:
      TZ: Europe/Dublin
    image: linuxserver/sonarr
    networks:
      - media_network
    ports:
      - '8989:8989'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/sonarr/config:/config
      - ${CACHE_LOCATION}/sabnzbd/downloads:/downloads
      - ${DATA_LOCATION}/jellyfin/media/Shows:/tv
  ombi:
    container_name: ombi
    environment:
      TZ: Europe/Dublin
    image: lscr.io/linuxserver/ombi:latest
    networks:
      - media_network
    ports:
      - '3579:3579'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/ombi/config:/config
  immich-server:
    container_name: immich_server
    depends_on:
      - redis
      - database
    environment:
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich_postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      TZ: Europe/Dublin
      UPLOAD_LOCATION: ${DATA_LOCATION}/immich/
    image: ghcr.io/immich-app/immich-server:release
    networks:
      - media_network
    ports:
      - '2283:2283'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/immich:/usr/src/app/upload
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    networks:
      - media_network
    restart: unless-stopped
    volumes:
      - model-cache:/cache
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    networks:
      - media_network
    restart: unless-stopped
  database:
    container_name: immich_postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      TZ: Europe/Dublin
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    networks:
      - media_network
    shm_size: 128mb
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/immich/pg_database:/var/lib/postgresql/data
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_ROLLING_RESTART=true
    restart: unless-stopped
    networks:
      - media_network
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.jasonntmk.com"
    volumes:
      - ${DATA_LOCATION}/vaultwarden:/data/
    ports:
      - '7456:80'
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_VULKAN=1
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${DATA_LOCATION}/ollama:/root/.ollama
    restart: unless-stopped
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ${DATA_LOCATION}/open-webui:/app/backend/data
    restart: unless-stopped
  wyoming-whisper:
    image: rhasspy/wyoming-whisper
    container_name: wyoming-whisper
    command: >
      --model small
      --language en
    ports:
      - "10300:10300"
    restart: unless-stopped
volumes:
  model-cache: null
  ollama:
  open-webui: