services:
    jellyfin:
        image: linuxserver/jellyfin
        container_name: jellyfin
        restart: unless-stopped
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [ gpu ]
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        networks:
          - default
        volumes:
          - /mediaServer/jellyfin/config:/config
          - /Media/jellyfin/media:/media
        ports:
          - 8096:8096
    sabnzbd:
      image: lscr.io/linuxserver/sabnzbd:latest
      container_name: sabnzbd
      environment:
        TZ: Europe/Dublin
        PUID: $UID
        PGID: $GID
      volumes:
        - /mediaServer/sabnzbd/config:/config
        - /mediaServer/sabnzbd/downloads:/downloads
        - /mediaServer/sabnzbd/incomplete:/incomplete-downloads
      ports:
        - 6789:8080
      restart: unless-stopped
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: unless-stopped
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        depends_on:
            - sabnzbd
        volumes:
            - /mediaServer/sonarr/config:/config
            - /mediaServer/sabnzbd/downloads:/downloads
            - /Media/jellyfin/media/Shows:/tv
        ports:
            - 8989:8989
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: unless-stopped
        environment:
          TZ: Europe/Dublin
          PUID: $UID
          PGID: $GID
        depends_on:
            - sabnzbd
        volumes:
            - /mediaServer/radarr/config:/config
            - /mediaServer/sabnzbd/downloads:/downloads
            - /Media/jellyfin/media/Movies:/movies
        ports:
            - 7878:7878
    ombi:
      image: lscr.io/linuxserver/ombi:latest
      container_name: ombi
      restart: unless-stopped
      environment:
        TZ: Europe/Dublin
        PUID: $UID
        PGID: $GID
      volumes:
        - /mediaServer/ombi/config:/config
      ports:
        - 3579:3579

    immich-server:
      container_name: immich_server
      image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
      environment:
        PUID: $UID
        PGID: $GID
      volumes:
        - ${UPLOAD_LOCATION}:/usr/src/app/upload
      env_file:
        - .env
      ports:
        - 2283:2283
      depends_on:
        - redis
        - database
      restart: always

    immich-machine-learning:
      container_name: immich-machine-learning
      image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
      environment:
        PUID: $UID
        PGID: $GID
      volumes:
        - model-cache:/cache
      env_file:
        - .env
      restart: always

    redis:
      container_name: immich_redis
      image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
      restart: always

    database:
      container_name: immich_postgres
      image: tensorchord/pgvecto-rs:pg14-v0.2.0
      env_file:
        - .env
      environment:
        TZ: Europe/Dublin
        PUID: $UID
        PGID: $GID
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE_NAME}
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
    volumes:
      pgdata:
      model-cache: