services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      TZ: Europe/Dublin
    volumes:
      - ${DATA_LOCATION}/jellyfin/config:/config
      - ${DATA_LOCATION}/jellyfin/media:/media
    ports:
      - "8096:8096"
  radarr:
    container_name: radarr
    depends_on:
      - sabnzbd
    environment:
      TZ: Europe/Dublin
    image: linuxserver/radarr
    ports:
      - '7878:7878'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/radarr/config:/config
      - ${DATA_LOCATION}/sabnzbd/downloads:/downloads
      - ${DATA_LOCATION}/jellyfin/media/Movies:/movies
  sabnzbd:
    container_name: sabnzbd
    environment:
      TZ: Europe/Dublin
    image: lscr.io/linuxserver/sabnzbd:latest
    ports:
      - '6789:8080'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/sabnzbd/config:/config
      - ${DATA_LOCATION}/sabnzbd/downloads:/downloads
      - ${DATA_LOCATION}/sabnzbd/incomplete:/incomplete-downloads
  sonarr:
    container_name: sonarr
    depends_on:
      - sabnzbd
    environment:
      TZ: Europe/Dublin
    image: linuxserver/sonarr
    ports:
      - '8989:8989'
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/sonarr/config:/config
      - ${DATA_LOCATION}/sabnzbd/downloads:/downloads
      - ${DATA_LOCATION}/jellyfin/media/Shows:/tv
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      TZ: Europe/Dublin
    volumes:
      - ${DATA_LOCATION}/ombi/config:/config
    ports:
      - "3579:3579"

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${DATA_LOCATION}/immich:/usr/src/app/upload
    environment:
      TZ: Europe/Dublin
      UPLOAD_LOCATION: ${DATA_LOCATION}/immich/
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      TZ: Europe/Dublin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DATA_LOCATION}/immich/pg_database:/var/lib/postgresql/data
    restart: always
volumes:
  model-cache: