version: '2'
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    restart: unless-stopped
    environment:
      TZ: Europe/Dublin
      PUID: $UID
      PGID: $GID
    volumes:
      - /mediaServer/nzbget/config:/config
      - /Media/nzbget/downloads:/downloads
    ports:
      - 6789:6789
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      TZ: Europe/Dublin
      PUID: $UID
      PGID: $GID
    depends_on:
      - nzbget
    volumes:
      - /mediaServer/sonarr/config:/config
      - /Media/nzbget/downloads:/downloads
      - /Media/jellyfin/media/Shows:/tv
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      TZ: Europe/Dublin
      PUID: $UID
      PGID: $GID
    depends_on:
      - nzbget
    volumes:
      - /mediaServer/radarr/config:/config
      - /Media/nzbget/downloads:/downloads
      - /Media/jellyfin/media/Movies:/movies
    ports:
      - 7878:7878
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      TZ: Europe/Dublin
      PUID: $UID
      PGID: $GID
    volumes:
      - /mediaServer/ombi/config:/config
    ports:
      - 3579:3579
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: Europe/Dublin
      PUID: $UID
      PGID: $GID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock