services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    environment:
      - TZ=Europe/Dublin
      - VIRTUAL_PORT=9090
      - VIRTUAL_PROTO=http
    volumes:
      - /monitoringServer/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Dublin
      - GF_SECURITY_ADMIN_USER=jason
      - GF_SECURITY_ADMIN_PASSWORD=Jqwe123!!
      - GF_SMTP_ENABLED=false
      - GF_SERVER_DOMAIN=grafana.jasonntmk.com
      - GF_SERVER_ROOT_URL=http://grafana.jasonntmk.com
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data:
  prometheus_data: