scrape_configs:
  - job_name: 'monitors PIs'
    static_configs:
      - targets: [ '192.168.0.29:9100' ]
        labels:
          service: 'monitoring-server'
      - targets: [ '192.168.0.30:9100' ]
        labels:
          service: 'automation-server'
      - targets: [ '192.168.0.31:9100' ]
        labels:
          service: 'network-server'
    metrics_path: /metrics
    scrape_interval: 60s